// Product catalog for Pipeline deal entry — mirrors the reference prototype's PRODUCTS list.
// No backend model yet (Pipeline/Order store cat/product as free-text strings); ported here so
// the create/edit forms offer the same categories/titles instead of free typing.
export const PRODUCTS = [
  { cat: 'Fixed', title: 'Business Pro New' },
  { cat: 'Fixed', title: 'Business Pro Mig' },
  { cat: 'Fixed', title: 'Business On New' },
  { cat: 'Fixed', title: 'Business On Mig' },
  { cat: 'Fixed', title: 'SOHO' },
  { cat: 'Fixed', title: 'BQS' },
  { cat: 'Fixed', title: 'Office Presence' },
  { cat: 'Fixed', title: 'Dell / PABX' },
  { cat: 'Fixed', title: 'Toll Free' },
  { cat: 'Fixed', title: 'Digital Internet' },
  { cat: 'Fixed', title: 'Digital Premium Internet' },
  { cat: 'Fixed', title: 'SIP Trunk' },
  { cat: 'Fixed', title: 'PRI' },
  { cat: 'Fixed', title: 'SD WAN' },
  { cat: 'Fixed', title: 'Business TV' },
  { cat: 'Fixed', title: 'Business Flat Plus' },
  { cat: 'Fixed', title: 'Business Super' },
  { cat: 'Fixed', title: 'Add Lines' },
  { cat: 'Fixed', title: 'Global MPLS' },
  { cat: 'Mobile', title: 'ATL Plans' },
  { cat: 'Mobile', title: 'BTL Plans' },
  { cat: 'Mobile', title: 'Data Sims' },
  { cat: 'Digital', title: 'UTAP' },
  { cat: 'Digital', title: 'Office 365' },
  { cat: 'Digital', title: 'Online Marketing' },
  { cat: 'Digital', title: 'VSAAS' },
  { cat: 'Digital', title: 'DGTX' },
  { cat: 'Digital', title: 'M2M' },
  { cat: 'Digital', title: 'SVT' },
  { cat: 'Digital', title: 'APP 360' },
  { cat: 'Digital', title: 'Social eCommerce' },
  { cat: 'Digital', title: 'Cloud' },
  { cat: 'Digital', title: 'SMS' },
];

export const PRODUCT_CATEGORIES = [...new Set(PRODUCTS.map((p) => p.cat))];
